### ISSUE TITLE
Library does not support the use of Master Key Files

### ISSUE THREAD

**Issue by pessimism** [adamfisher/KeePass.Extensions.Configuration#2]
Library supports windows user account, password, or unauthenticated variants of KeyPass databases but does not support master key files.  Supporting these would be greatly appreciated as our organization requires use of both a master key file and a password to protect our databases.

**Comment by adamfisher** [comment]
You can use the override extension method to pass a composite key instead of a master password. These are the possible inputs below.

```csharp
var compositeKey = new CompositeKey()
[
    new KcpKeyFile(masterKeyFilePath),     // Use master key file
    new KcpPassword("MyMasterPassword"),   // Use master password
    new KcpUserAccount()                   // Use Windows account
    new KcpCustomKey(...)                  // Create a custom key
];
```

It sounds like you want to just pass use `KcpKeyFile` so you would just use:
```csharp
configuration.AddKeePass(pathToDbx, new CompositeKey() [ new KcpKeyFile(pathToMasterKeyFile)]);
```
